### ISSUE TITLE
Add commands for SSID Scan results

### ISSUE THREAD

**Issue by PropGit** [dbetz/Parallax-ESP#12]
[EDITED due to [second post's](https://github.com/parallaxinc/Parallax-ESP/issues/12#issuecomment-271034030) info]
Add ~~Network and~~ Serial command~~s~~ to scan for SSIDs.  The intent is that this returns a string containing multiple substrings, each of which is an SSID that it found during a scan.

**Comment by dbetz** [comment]
There is already a network API for scanning for access points. That is what the configuration web page uses.

**Comment by dbetz** [comment]
To add a bit more information, the network API for initiating a scan and returning discovered access points is "/wifi/wifiscan.cgi". It returns a JSON response that contains the access points discovered on the previous call to "/wifi/wifiscan.cgi". The format of the JSON reply is:

When the scan is still in progress:

```
{
  "result": {
    "inProgress": 1
  }
}
```
When the scan completes:

```
{
  "result": {
    "inProgress": 0,
    "APs": [
      { "essid": "x",
        "bssid": "x",
        "rssi": "x",
        "enc": "x",
        "channel": "x"
      },
      (more entries as above)
    ]
  }
}
```

Where "x" above indicates the value of the associated field.

**Comment by dbetz** [comment]
Is the existing network API for scanning as described above okay or do we need a different network API?

**Comment by PropGit** [comment]
> Is the existing network API for scanning as described above okay or do we need a different network API?

The existing network API is fine as-is.

**Comment by PropGit** [comment]
UPDATE: So far we've settled on the commands APSCAN (to start the Wi-Fi Scan process) and APGET (to retrieve the found Wi-Fi SSIDs).

QUESTION: Should we return only SSIDs?  Or should we also return the security type and/or other associated information, such as items listed by the Network API?

We're considering providing the response as __S, ssid, enc__  where _ssid_ is the SSID and _enc_ is the encoding/security type, a numeric value that relates to one of OPEN, WEP, WPA_PSK, WPA2_PSK, and WPA_WPA2_PSK.  We'll define the number/type pairs in documentation.

**Comment by PropGit** [comment]
@dbetz - Maybe we should think about this a bit more.  Would it be possible to filter the results by encryption type or simple search strings, like "xyz," which would return SSIDs _Wxyz_, and _AbcXYz_, but not _Linksys_, or _FreeWiFi_, for example.

**Comment by dbetz** [comment]
Actually the ESP API allows some filtering that doesn't get used currently. They can filter by SSID, BSSID, channel number, or whether the AP is hidden. There is no pattern matching on SSID though.

**Comment by PropGit** [comment]
UPDATE: v2017-01-19-0828 includes the APSCAN and APGET Serial API commands.

__APSCAN__ 
  * takes no arguments
  * returns "S,0"
  * if events are enabled, an event “A,count,0” arrives when the scan completes

__APGET__ 
  * takes a single argument, a numeric value from 0 to N-1 where N is the number of access points found during the scan.
  * returns “N,0” if the scan is not yet complete
  * returns "E,code" if an out-of-range value is given
  * returns “S,enc,ssid” if the scan has completed.  The contents relate to the item given by the APGET argument.
    * enc is an enumerated value indicating the security encryption type
    * ssid is the SSID string

**Comment by dbetz** [comment]
Can this be closed?

**Comment by PropGit** [comment]
@AndyLindsay - This feature is now in the new firmware as described above.  Does this meet your needs?  Have you had a chance to test it yet?

**Comment by AndyLindsay** [comment]
Thank you, I have not been able to test it.  I'm having some computer
hardware problems, and everything is going at a snail's pace right now.

**Comment by AndyLindsay** [comment]
I just got another report of the same symptom.

Any info you can get from them about OS, browser, setup, security settings
and security software that might be causing the problem would be
appreciated.

**Comment by PropGit** [comment]
> I just got another report of the same symptom.

@AndyLindsay - Was that post really intended for this issue?

**Comment by PropGit** [comment]
Leaving this issue for @AndyLindsay Andy to test and respond when he has time.  Please report and close the issue (if tested successfully).

**Comment by PropGit** [comment]
We don't anticipate problems with this; closing the issue.
