### ISSUE TITLE
Name to SSID: Verify and add rules

### ISSUE THREAD

**Issue by PropGit** [dbetz/Parallax-ESP#14]
Verify that Module Name changes are being reflected as the SSID.  This seems to work sometimes and not others (PropGit witnessed differences between using his workstation and a tech support workstation but has not retested).

Apply PropLoader's module name rules to firmware to limit name (and thus SSID) to safe characters.

**Comment by dbetz** [comment]
Have you tried this with the latest firmware? A forum member reported this a while back and I thought I had fixed it.

**Comment by PropGit** [comment]
I have not... but I have a faint memory of what you're describing too.  One of us will have to check it out before resolving this item.

**Comment by PropGit** [comment]
I will have to retest this using my system at home office and tech support's system at Rocklin office to verify.

**Comment by dbetz** [comment]
Did this ever get tested? Can it be closed?

**Comment by PropGit** [comment]
@dbetz - No it didn't, but I can test tomorrow morning using the same scenario as before.  I will make the effort to do so.

**Comment by PropGit** [comment]
Verified that this works now.  Tried "Save to Flash" each time.
