### ISSUE TITLE
Add Serial API command to retrieve IP Address

### ISSUE THREAD

**Issue by PropGit** [dbetz/Parallax-ESP#15]
Add a Serial API command to retrieve the STA IP Address and the AP IP Address.

**Comment by dbetz** [comment]
Try the "station-ipaddr" and "softap-ipaddr" settings.

**Comment by dbetz** [comment]
Can this be closed?

**Comment by PropGit** [comment]
Needs confirmation testing on our side first.  We'll close when test verified.

**Comment by PropGit** [comment]
I've created a label to mark this as "Needs Testing."

**Comment by AndyLindsay** [comment]
I have not stress tested it, but in the as-I-go usage cases, it has been working well.

**Comment by PropGit** [comment]
@AndyLindsay - Can we consider this issue resolved now?
