### ISSUE TITLE
Add "Home" Link to Each Web Page (other than the Home page)

### ISSUE THREAD

**Issue by PropGit** [dbetz/Parallax-ESP#3]
On the Wi-Fi Networks page
![image](https://cloud.githubusercontent.com/assets/1266318/16235941/69c37562-378b-11e6-821a-47f5fe7b91c2.png)

... Upload page
![image](https://cloud.githubusercontent.com/assets/1266318/16235957/7322cf90-378b-11e6-95e8-e6650b8f9521.png)

... Settings page
![image](https://cloud.githubusercontent.com/assets/1266318/16235971/79b4cc78-378b-11e6-8a54-a53e4dd571e4.png)

... and the Firmware Update web page,
![image](https://cloud.githubusercontent.com/assets/1266318/16235982/88b4efa0-378b-11e6-90f9-9e28e6399df2.png)

Please add a "Home" link, or button, that takes the user back to the home page.
![image](https://cloud.githubusercontent.com/assets/1266318/16236006/9d44599c-378b-11e6-85b0-bef0afbed195.png)

**Comment by dbetz** [comment]
NP. Do you have a graphic you'd like to use for the button?

**Comment by dbetz** [comment]
I uploaded a firmware update that puts a navigation bar on the left side of the screen that will allow you to jump from any page to any other page including the home page.

**Comment by PropGit** [comment]
I like the navigation bar effort but have yet to try it.  I'm concerned about responsive layout on constrained screens (smartphones in portrait orientation, especially).

If the nav bar makes it difficult to use on constrained screens, short of adding responsive layout features, we'd probably opt for a single link.  Before you added the nav bar, I asked our web/graphic artist for input and she suggested the following two possibilities that I'm adding here just in case we need to revert to it.  See lower-right of each image.

In the meantime, no need to make any more changes until I test and respond with an additional post.

![return](https://cloud.githubusercontent.com/assets/1266318/16458207/290b4e8e-3dd3-11e6-808f-c191f6ba47e9.png)

![returnhome](https://cloud.githubusercontent.com/assets/1266318/16458219/2dc5c8f0-3dd3-11e6-8d30-0adf20717cd9.png)

**Comment by PropGit** [comment]
Closing because I believe this issue has been fully addressed now.
