### ISSUE TITLE
Module unresponsive after multiple user filesystem updates

### ISSUE THREAD

**Issue by PropGit** [dbetz/Parallax-ESP#35]
After updating a file multiple times in the user filesystem, the module becomes unresponsive (even after power cycle) and can not be recovered except with a wired firmware refresh.

**Comment by PropGit** [comment]
@dbetz looked into this and found that the user filesystem code was in error, causing filesystem overruns to be possible.

**Comment by dbetz** [comment]
Yes, I'm in the process of fixing this.

**Comment by dbetz** [comment]
I just pushed a fix to this problem.
