### ISSUE TITLE
Need to add Command Events (enabled/disabled) to Settings page

### ISSUE THREAD

**Issue by PropGit** [dbetz/Parallax-ESP#5]
The Network Interface includes the **cmd-events** command, but the Settings page does not:

![image](https://cloud.githubusercontent.com/assets/1266318/18897048/9f16a4a8-84db-11e6-81ff-358ed45962bf.png)

We need to add a setting for this, similar to "Serial Commands"

**Comment by dbetz** [comment]
This has been added.
