### ISSUE TITLE
Can DBG be disabled by default and/or can DBG output be filtered?

### ISSUE THREAD

**Issue by PropGit** [dbetz/Parallax-ESP#9]
**UPDATED**
~~@dbetz - Can you think of a way that we could set DBG to be optional and disabled by default?  Some way that doesn't prevent us from using DBG for our uses (development) in all the cases we need it to be?~~

We solved this immediate need with [this solution](https://github.com/parallaxinc/Parallax-ESP/issues/9#issuecomment-253672289).

**Comment by dbetz** [comment]
Unfortunately, most of those messages are printed by os_printf which, as far as I know, isn’t switchable. They should probably all be switched over to some new function like dbg_printf that maybe would take an extra argument indicating the type of message along with a way to select specific messages to print. That way you could, say, enable all CMD handling messages or all wi-fi status messages, or all HTTP messages, etc.

**Comment by PropGit** [comment]
Okay, let's consider this for Release 2, among others.

**Comment by PropGit** [comment]
**Update** - Andy determined that he could set the DBG to input via a **CHECK:gpio_xxx** command at the start of the PBASIC example code... that allows us to use P12 in the BOE for servo control and it won't be affected by DBG.  Perfect; problem solved.

So, the ability to filter DBG output is how this issue can proceed, but it's purely helpful for development purposes and no longer an issue for our tutorials or for users.  It can proceed at a pace conducive to it's need for us developers.

**Comment by dbetz** [comment]
This is done. There is a setting that enables/disables output to the DBG pin. The default is "disabled". There is also a "Debug Log" page in the web interface that shows the most recent 1400 bytes of debug output.

**Comment by PropGit** [comment]
Closing.
